### ISSUE TITLE
Create the game v1

### ISSUE THREAD

**Issue by eslutz** [eslutz/Space-Adventure-Text-Game#11]
Put these pieces together to get a working game:

### Steps:

- [x] Game introduction/instructions
- [x] Help function to display instructions
- [x] Display current status (room, inventory, any item in the room)
- [x] Get action input/verify valid input
- [x] Move between rooms ([movement](https://github.com/eslutz/Space-Adventure-Text-Game/issues/2))
  - [x] Check if villain is in the room
- [x] Pickup items ([pickup](https://github.com/eslutz/Space-Adventure-Text-Game/issues/3))
  - [x] Check if all items collected
- [x] Update documentation ([docs](https://github.com/eslutz/Space-Adventure-Text-Game/issues/4))

### Requirements:

- Use a dictionary in main() linking rooms and items
- Player wins by collecting all items
- Player loses by running into the villain

**Comment by eslutz** [comment]
All features completed.
